import type { SiteConfig, NavItem, LoanProgram, Property } from '@/types'

export const siteConfig: SiteConfig = {
  name: 'Arrowhead Realty & Mortgage',
  nmls: '1429245',
  dre: '01847350',
  phone: '(888) 777-3556',
  email: 'info@arrowheadmtg.com',
  address: {
    street: '225 W. Hospitality Lane, Ste. 201F',
    city: 'San Bernardino',
    state: 'CA',
    zip: '92408',
  },
  serviceAreas: [
    'San Bernardino',
    'Fontana',
    'Rialto',
    'Ontario',
    'Rancho Cucamonga',
    'Redlands',
    'Colton',
    'Highland',
  ],
}

export const navigation: NavItem[] = [
  { label: 'Home', href: '/' },
  { label: 'Mortgage', href: '/mortgage' },
  { label: 'Real Estate', href: '/real-estate' },
  { label: 'Calculators', href: '/calculators' },
  { label: 'About', href: '/about' },
  { label: 'Contact', href: '/contact' },
]

export const loanPrograms: LoanProgram[] = [
  {
    id: 'conventional',
    name: 'Conventional Loans',
    description:
      'Traditional financing with competitive rates for qualified borrowers.',
    features: [
      'Down payments as low as 3%',
      'Flexible terms (15, 20, 30 years)',
      'No upfront mortgage insurance',
      'Primary, secondary, or investment properties',
    ],
  },
  {
    id: 'fha',
    name: 'FHA Loans',
    description:
      'Government-backed loans ideal for first-time buyers and those with lower credit scores.',
    features: [
      'Down payments as low as 3.5%',
      'More flexible credit requirements',
      'Lower closing costs',
      'Assumable loans',
    ],
  },
  {
    id: 'va',
    name: 'VA Loans',
    description:
      'Exclusive benefits for veterans, active military, and eligible spouses.',
    features: [
      'No down payment required',
      'No private mortgage insurance',
      'Competitive interest rates',
      'Limited closing costs',
    ],
  },
  {
    id: 'jumbo',
    name: 'Jumbo Loans',
    description:
      'Financing for high-value properties that exceed conventional loan limits.',
    features: [
      'Loan amounts above conforming limits',
      'Competitive rates for qualified borrowers',
      'Various term options',
      'Primary and secondary homes',
    ],
  },
]

// Sample property listings (replace with real data from API/database)
export const sampleProperties: Property[] = [
  {
    id: '1',
    slug: '1234-oak-street-san-bernardino',
    status: 'for-sale',
    price: 485000,
    address: {
      street: '1234 Oak Street',
      city: 'San Bernardino',
      state: 'CA',
      zip: '92410',
    },
    bedrooms: 4,
    bathrooms: 2.5,
    sqft: 2150,
    lotSize: 6500,
    yearBuilt: 2018,
    propertyType: 'single-family',
    description: 'Beautiful modern home in a quiet neighborhood. Features an open floor plan, updated kitchen with granite countertops, and a spacious backyard perfect for entertaining.',
    features: [
      'Central A/C',
      'Attached 2-car garage',
      'Stainless steel appliances',
      'Hardwood floors',
      'Walk-in closets',
      'Covered patio',
    ],
    images: [
      '/img/properties/placeholder-1.jpg',
      '/img/properties/placeholder-2.jpg',
      '/img/properties/placeholder-3.jpg',
      '/img/properties/placeholder-4.jpg',
    ],
    mlsNumber: 'CV24123456',
    daysOnMarket: 12,
    createdAt: '2024-01-15',
    updatedAt: '2024-01-15',
  },
  {
    id: '2',
    slug: '567-palm-ave-fontana',
    status: 'for-sale',
    price: 625000,
    address: {
      street: '567 Palm Avenue',
      city: 'Fontana',
      state: 'CA',
      zip: '92335',
    },
    bedrooms: 5,
    bathrooms: 3,
    sqft: 2850,
    lotSize: 8000,
    yearBuilt: 2020,
    propertyType: 'single-family',
    description: 'Stunning newer construction with premium finishes throughout. Gourmet kitchen, primary suite with retreat, and solar panels included.',
    features: [
      'Solar panels (owned)',
      'Smart home features',
      'Quartz countertops',
      'Primary suite retreat',
      'Tankless water heater',
      'Low-maintenance landscaping',
    ],
    images: [
      '/img/properties/placeholder-2.jpg',
      '/img/properties/placeholder-1.jpg',
      '/img/properties/placeholder-3.jpg',
    ],
    mlsNumber: 'CV24123457',
    daysOnMarket: 5,
    createdAt: '2024-01-20',
    updatedAt: '2024-01-20',
  },
  {
    id: '3',
    slug: '890-sunset-blvd-rialto',
    status: 'pending',
    price: 399000,
    address: {
      street: '890 Sunset Boulevard',
      city: 'Rialto',
      state: 'CA',
      zip: '92376',
    },
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1650,
    lotSize: 5500,
    yearBuilt: 1995,
    propertyType: 'single-family',
    description: 'Well-maintained home with recent updates. New roof, updated bathrooms, and fresh interior paint. Great starter home or investment property.',
    features: [
      'New roof (2023)',
      'Updated bathrooms',
      'Fresh paint',
      'Large backyard',
      'RV parking',
      'Close to schools',
    ],
    images: [
      '/img/properties/placeholder-3.jpg',
      '/img/properties/placeholder-1.jpg',
      '/img/properties/placeholder-2.jpg',
    ],
    mlsNumber: 'CV24123458',
    daysOnMarket: 21,
    createdAt: '2024-01-05',
    updatedAt: '2024-01-25',
  },
  {
    id: '4',
    slug: '2100-highland-dr-redlands',
    status: 'for-sale',
    price: 875000,
    address: {
      street: '2100 Highland Drive',
      city: 'Redlands',
      state: 'CA',
      zip: '92374',
    },
    bedrooms: 5,
    bathrooms: 4,
    sqft: 3800,
    lotSize: 12000,
    yearBuilt: 2015,
    propertyType: 'single-family',
    description: 'Luxurious estate home with breathtaking mountain views. Chef\'s kitchen, home theater, wine cellar, and resort-style pool and spa.',
    features: [
      'Pool & spa',
      'Home theater',
      'Wine cellar',
      'Mountain views',
      'Outdoor kitchen',
      '3-car garage',
    ],
    images: [
      '/img/properties/placeholder-4.jpg',
      '/img/properties/placeholder-1.jpg',
      '/img/properties/placeholder-2.jpg',
      '/img/properties/placeholder-3.jpg',
    ],
    mlsNumber: 'CV24123459',
    daysOnMarket: 8,
    createdAt: '2024-01-18',
    updatedAt: '2024-01-18',
  },
  {
    id: '5',
    slug: '445-citrus-way-ontario',
    status: 'for-sale',
    price: 549000,
    address: {
      street: '445 Citrus Way',
      city: 'Ontario',
      state: 'CA',
      zip: '91762',
    },
    bedrooms: 4,
    bathrooms: 2.5,
    sqft: 2400,
    lotSize: 7200,
    yearBuilt: 2010,
    propertyType: 'single-family',
    description: 'Move-in ready home in desirable Ontario neighborhood. Open concept living, upgraded flooring, and beautifully landscaped front and back yards.',
    features: [
      'Open floor plan',
      'Upgraded flooring',
      'Stainless appliances',
      'Landscaped yards',
      'Community pool',
      'Near shopping',
    ],
    images: [
      '/img/properties/placeholder-1.jpg',
      '/img/properties/placeholder-4.jpg',
      '/img/properties/placeholder-2.jpg',
    ],
    mlsNumber: 'CV24123460',
    daysOnMarket: 15,
    createdAt: '2024-01-10',
    updatedAt: '2024-01-10',
  },
  {
    id: '6',
    slug: '789-mountain-view-rancho-cucamonga',
    status: 'sold',
    price: 725000,
    address: {
      street: '789 Mountain View Lane',
      city: 'Rancho Cucamonga',
      state: 'CA',
      zip: '91730',
    },
    bedrooms: 4,
    bathrooms: 3,
    sqft: 2650,
    lotSize: 6800,
    yearBuilt: 2017,
    propertyType: 'single-family',
    description: 'Elegant home with stunning curb appeal. Gourmet kitchen, spacious bedrooms, and a private backyard oasis with covered patio.',
    features: [
      'Gourmet kitchen',
      'Covered patio',
      'Private backyard',
      'His & hers closets',
      'Laundry room',
      'Epoxy garage floor',
    ],
    images: [
      '/img/properties/placeholder-2.jpg',
      '/img/properties/placeholder-3.jpg',
      '/img/properties/placeholder-4.jpg',
    ],
    mlsNumber: 'CV24123461',
    daysOnMarket: 45,
    createdAt: '2023-12-01',
    updatedAt: '2024-01-15',
  },
]
